---
  TRADE_OPTIONS:
    # In your pairing coin
    QUANTITY: 15
    # BTCUSDT will be bought for example
    PAIRING: USDT
    # How often to check for posts and run the script
    # in minutes
    RUN_EVERY: 0.025
    TEST: True
    SL: 3
    TP: 2
    ENABLE_TSL: True
    TSL: 4
    TTP: 2
  SEND_NOTIFICATIONS: True
  EMAIL_ADDRESS: 'your@email.address'
  EMAIL_PASSWORD: 'I'll let you figure out what this one is'
